<?php

namespace Database\Seeders;

use App\Models\Specialization;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SpecializationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $specializations = [
            "Acupuncture",
            "Acupuncture Physician",
            "Addiction Professional",
            "Administration and Clinical Cosmetology",
            "Aesthetic & Cosmetic Center",
            "Aesthetic and Cosmetic Surgeon",
            "Aesthetic Medicine And Cosmetologist",
            "Aesthetic Physician",
            "Aesthetic Physician and Cosmetologist",
            "Aesthetic Practitioner",
            "Allergy And Asthma Specialist",
            "Allergy And Immunology",
            "Allergy Specialist",
            "Ambulance Facility",
            "Ambulance Facility - Normal Patients",
            "Ambulatory Monitoring",
            "Anaesthetist",
            "Anaesthetist (Pain Management)",
            "Anaesthetist and Intensivist",
            "Andrology And Male Fertility",
            "Anesthetist Assistant",
            "Anomaly Scan",
            "Anomaly Scan 2",
            "Anomaly Scan 3",
            "Anorectal Surgeon",
            "Anorectal Surgeon (Ayurvedic)",
            "Applied Psychologist",
            "Art Therapist",
            "Arterial Doppler - One Leg",
            "Arterial Doppler - Two Legs",
            "Arthritis",
            "Arthritis and Spinal Disorders",
            "Assessment Sessions",
            "Associate Specialist in Oral and Maxillofacial Surgery",
            "Associate Specialist in Orthodontics",
            "Asthma Specialist",
            "Audio Grapher",
            "Audiologist",
            "Audiometrist",
            "Australia Visa Medical",
            "Ayurveda Kayachikitsa",
            "Ayurveda Neuroendocrinology",
            "Ayurveda Unani",
            "Ayurvedic And Alternative Medicine",
            "Ayurvedic Cardiologist",
            "Ayurvedic Dermatologist",
            "Ayurvedic General Slimming & Beauty",
            "Ayurvedic Gynaecologist",
            "Ayurvedic Physician",
            "Ayurvedic Physician (Boils & Wounds Special)",
            "Ayurvedic Skin Specialist",
            "Ayurvedic Surgeon",
            "AYUSH Children's Health",
            "AYUSH Full Body Therapy (Abhyanga & Swedana)",
            "AYUSH Holistic Health Assessment",
            "AYUSH Joint and Bone Health",
            "AYUSH Joint, Muscle and Bone Health",
            "AYUSH Leg Therapy (Padabhyanga)",
            "AYUSH Men's Health",
            "AYUSH Relaxation & Rejuvenation Therapy",
            "AYUSH Skin and Beauty",
            "AYUSH Women's Health",
            "Back Pain Treatment",
            "Bacteriologist",
            "Behaviour Therapist",
            "Biometry Test",
            "Bone / Spine Treatments",
            "Brain Training/ Rehabilitation Sessions",
            "Breast and Cancer Surgeon",
            "Breast and Oncological Surgeon",
            "Breast Cancer Surgeon",
            "Breast Care Clinic",
            "Breast Clinic",
            "Breast Feeding",
            "Breast Feeding Advisor",
            "Breastfeeding and Counselling",
            "Canada Visa Medical",
            "Cancer Surgeon",
            "Cardiac Electrophysiologist",
            "Cardiac Surgeon",
            "Cardiographer",
            "Cardiologist",
            "Cardiologist and Cardiac Electrophysiologist",
            "Cardiologist Echo",
            "Cardiothoracic Surgeon",
            "Carotid Doppler",
            "Chemical Pathologist",
            "Chemical Pathology",
            "Chest Physician",
            "Chest Specialist",
            "Child and Adolescent Psychiatric",
            "Child and Adolescent Psychologist",
            "Child And Adolescent Psychology Clinic",
            "Child Counselling Psychologist and Therapist",
            "Child Psychiatrist",
            "Child Psychologist",
            "Children Dentist",
            "Children Respiratory Chest Diseases, Wheezing and Asthma",
            "Children's Respiratory Centre",
            "Chiropractor",
            "Clinic Arrangements",
            "Clinical Geneticist",
            "Clinical Interventional Cardiologist",
            "Clinical Audiologist",
            "Clinical Embryologist",
            "Clinical Haematologist",
            "Clinical Health Psychologist",
            "Clinical Hypnotist",
            "Clinical Immunologist",
            "Clinical Microbiologist",
            "Clinical Neurologist",
            "Clinical Neurophysiologist",
            "Clinical Nutrition Physician",
            "Clinical Nutritionist",
            "Clinical Oncologist",
            "Clinical Physiologist",
            "Clinical Psychologist",
            "Co-Ordinating Dr (Sleep Medicine)",
            "Colorectal Surgeon",
            "Community & Development Paediatrician",
            "Community Child Health( Development Assessment )",
            "Community Dentistry",
            "Community Medicine",
            "Community Medicine Physician",
            "Community Paediatrician",
            "Consultant",
            "Consultant Anaesthetist",
            "Consultant Cancer Surgeon",
            "Consultant Cardiologist",
            "Consultant Cardiothoracic Surgeon",
            "Consultant Clinical Neurophysiologist",
            "Consultant Clinical Nutrition Physician",
            "Consultant Dental Surgeon",
            "Consultant Dermatologist",
            "Consultant Dietician / Medical Clinical Nutritionist",
            "Consultant Emergency Physician",
            "Consultant Endocrinologist",
            "Consultant ENT Surgeon",
            "Consultant Eye Surgeon",
            "Consultant Facial Surgeon",
            "Consultant Family Physician",
            "Consultant Gastrointestinal Surgeon",
            "Consultant Haematologist",
            "Consultant In Fertility",
            "Consultant in Orthodontics",
            "Consultant In Reproductive Medicine",
            "Consultant in Restorative Dentistry",
            "Consultant in Subfertility",
            "Consultant Judicial Medicine",
            "Consultant Nephrologist",
            "Consultant Nutrition Physician",
            "Consultant Nutritionist",
            "Consultant Obstetrician and Gynaecologist",
            "Consultant Oncologist",
            "Consultant Oncosurgeon",
            "Consultant Orthodontist",
            "Consultant Orthopaedic Surgeon",
            "Consultant Paediatric Neurologist",
            "Consultant Paediatric Pulmonologist",
            "Consultant Paediatrician",
            "Consultant Physician",
            "Consultant Psychiatrist",
            "Consultant Radiologist",
            "Consultant Respiratory Physician",
            "Consultant Sports and Exercise Medicine",
            "Consultant Surgeon",
            "Consultant Surgical Oncologist",
            "Consultant Thoracic Surgeon",
            "Consultant Urological Surgeon",
            "Consultation and Vaccinations",
            "Corneal Surgeon",
            "Coronary Angiogram",
            "Cosmetic and Breast Cancer Surgeon",
            "Cosmetic Care Clinic and Cosmetic",
            "Cosmetic Care Clinic and Cosmetic Physician",
            "Cosmetic Center",
            "Cosmetic Clinic",
            "Cosmetic Dentistry",
            "Cosmetic Dermatology",
            "Cosmetic Gynaecology",
            "Cosmetic Oculoplasty",
            "Cosmetic Physician",
            "Cosmetic Skincare",
            "Cosmetologist",
            "Counseling Psychologist",
            "Counselling",
            "Counselor",
            "Counselor and Psychotherapist",
            "Couple Counselor",
            "Critical Care Medicine",
            "Critical Care Physician(Consultant Intensivist)",
            "CT Coronary Angiogram",
            "CTG",
            "Cupping Therapist",
            "Cystoscopy",
            "Dental And Maxillo - Facial Surgeon",
            "Dental Implantologist",
            "Dental Surgeon",
            "Dental Surgeon (Preventive Dentistry)",
            "Dental Surgeon - Cosmetic Dentistry",
            "Dental Surgeon - Paedodontics",
            "Dental Surgeon / General And Laser",
            "Dental Surgeon In Prosthodontics And Endodontics",
            "Dentist",
            "Dermatologist",
            "Dermatologist (Adult & Paediatric)",
            "Diabetic Educator",
            "Diabetic Foot Care",
            "Diabetic Specialist",
            "Diabetologist",
            "Dietary and Nutrition",
            "Dietician",
            "Dietician & Nutritionist",
            "Dietician AND/OR public health nutritionist",
            "Doppler Scan",
            "Dressing",
            "Ear Piercing",
            "Ear, Nose and Throat Surgeon",
            "ECG",
            "ECHO Scan",
            "Educational Therapist",
            "EEG",
            "EEG Technician",
            "Elderly And Memory Practices",
            "Elderly Care",
            "Elderly Medicine",
            "Electroencephalography Specialist",
            "Electromyogram (EMG) Test & Nerve Conduction Study (NCS)",
            "Embryologist",
            "EMDR Therapist",
            "Emergency Medicine",
            "Emergency Physician",
            "Endocrinologist",
            "ENDOMETRIAL BIOPSY",
            "ENT - Head And Neck Surgeon",
            "ENT Surgeon",
            "Exercise ECG",
            "Eye Allergies and Eye Surgeon",
            "Eye Diseases/Rheumatologist(Traditional Medicine)",
            "Eye Surgeon",
            "Face & Jaw Surgeon",
            "Facial Plastic Surgeon",
            "Family And General Counsellor",
            "Family Counseling and Career Guidance",
            "Family Counselling",
            "Family Medicine",
            "Family Physician",
            "Family Planning /Reproductive And Female Sexual Health",
            "Family Planning Clinic",
            "Fellowship In Aesthetic Medicine",
            "Fertility Consultant",
            "Fertility Counselor",
            "Fertility Physician",
            "Fertility Specialist",
            "Food & Nutrition",
            "Forensic Medicine",
            "Forensic Psychiatrist",
            "Gastroenterological And Bariatric Surgeon",
            "Gastroenterological And Hepatobiliary Surgeon",
            "Gastroenterological Surgeon",
            "Gastroenterologist",
            "Gastrointestinal Surgeon",
            "General",
            "General and Gastroenterological Surgeon",
            "General And Colorectal Surgeon",
            "General and Endocrine Surgeon",
            "General and Hepato-Pancreato-Biliary(HPB) Surgeon",
            "General and Laparoscopic Surgeon",
            "General Counselling",
            "General Medical Practitioner",
            "General Medical Services",
            "General Medicine",
            "General Paediatrician",
            "General Physician",
            "General Practitioner",
            "General Surgeon",
            "Genereal and Interventional Cardiologist",
            "Genetic Counselor",
            "Geneticist",
            "Genito Urinary Surgeon",
            "Geriatric Medicine",
            "Geriatric Physician",
            "Geriatrician/ Elderly Care Specialist",
            "Guided Aspiration",
            "Guided FNAC",
            "Guided Injections",
            "Gynae Oncology",
            "Gynaecological Cancer Surgeon",
            "Gynaecological Oncologist",
            "Gynaecological Oncosurgeon",
            "Gynaecological Scan",
            "Gynaecologist",
            "Gynaecologist (VOG)",
            "Gynaecologist In Subfertility",
            "Gynaecology and Obstetrics - Unani",
            "Gynaecology Clinic (Ward 01 & 02)",
            "Gynaecology Clinic (Ward 03 & 04)",
            "Gynaecology Clinic (Ward 05 & 06)",
            "Gynaecology Clinic (Ward 07 & 08)",
            "Gynaecology Clinic (Ward 09 & 10)",
            "Gynecologist and Consultant in Fertility",
            "Haemato-oncologist",
            "Haematologist",
            "Hair Clinic",
            "Hair Restoration Transplant",
            "Hair Transplant",
            "Health & Fitness Specialist",
            "Health Check-up & Medical Screening Services - Nawaloka Medicare Gampaha",
            "Health Management",
            "Healthcare Package",
            "Healthy Weight Program - Visit 1",
            "Healthy Weight Program - Visit 2",
            "Healthy Weight Program - Visit 3",
            "Heamatologist",
            "Hepatobiliary Liver Transplant Surgeon",
            "Hepatobiliary Surgeon",
            "Hepatologist",
            "Hernia Centre",
            "Histopathologist",
            "Holter Monitoring",
            "Home Visit",
            "Homeopathy",
            "Homeopathy Physician",
            "Hormonal Imbalances",
            "Hospital Facility Tour",
            "HSG",
            "Human Nutritionist",
            "Hydrotherapy",
            "Hypnotherapist",
            "Hypnotist",
            "Imago Therapist",
            "Immunologist",
            "IMPLANT REMOVE",
            "Implantologist",
            "Infertility",
            "Injection Service",
            "Insomnia Treatments",
            "Internal Medicine",
            "Interventional Cardiologist",
            "Interventional Radiologist",
            "IUCD",
            "IUI 1ST",
            "IUI 2ND",
            "IVF Specialist",
            "Kidney Dialysis",
            "Kidney Transplant Surgeon",
            "Lab Sample Collection",
            "Lactation Counseling",
            "Laparoscopic and Bariatric Surgeon",
            "Laparoscopy And Colorectal Surgeon",
            "Laser Hair Removal",
            "Laser Removal",
            "Life Coach",
            "Life Style Management For Weight Loss and Diabetes",
            "Lifestyle Medicine",
            "Lifestyle Therapist",
            "Liver Centre",
            "Low Vision Practitioner",
            "Lung Function Test",
            "Manual Therapist",
            "Manual Therapist",
            "Massage Therapist",
            "Maxillofacial Surgeon",
            "Medical Aesthetist",
            "Medical And Clinical Geneticist",
            "Medical Examination (Visa)",
            "Medical Fitness Certificate for Sports",
            "Medical Gastroenterologist",
            "Medical Laser Therapist & Esthetics Technician",
            "Medical Microbiologist",
            "Medical Nutritionist",
            "Medical Officer",
            "Medical Officer - Home Visit",
            "Medical Officer - Nutrition",
            "Medical Officer - Ophthalmology",
            "Medical Parasitologist",
            "Medical Psychologist",
            "Medical Virologist",
            "Memory and Cognitive Assessment",
            "Memory Clinic",
            "Mens Sexual And Reproductive Health",
            "Menstrual Disorder Clinic",
            "Mental Health Counselor",
            "Microbiologist",
            "Mother and Baby Care Consultant",
            "Music Therapist",
            "Mycologist",
            "Nebulization",
            "Neonatal Paediatrician",
            "Neonatologist",
            "Nephrologist",
            "Nerve Conduction",
            "Neuro Physician",
            "Neuro Physiologist",
            "Neuro Physiotherapy",
            "Neuro Surgeon",
            "Neurologist",
            "New Zealand Visa Medical",
            "Newborn Hearing Screening",
            "NT - Scan",
            "Nutrition Physician",
            "Nutrition Specialist",
            "Nutritionist",
            "Nutritious Advice",
            "Obstetrician",
            "Obstetrician & Gynaecologist",
            "Obstetrician & Gynaecologist (Follow-Up)",
            "Obstetrician & Gynaecologist (New Patients)",
            "Obstetrician And Fetal Medicine Specialist",
            "Obstetrician, Fetal Medicine Specialist & Genetic Consultation",
            "Occupational Medicine",
            "Occupational Physician",
            "Occupational Therapist",
            "Oculoplastic Surgeon",
            "OMF Surgeon",
            "OMF Surgeon & Specialist in Oral Medicine",
            "Oncological Surgeon",
            "Oncologist",
            "Oncologist - Cancer Specialist",
            "OPD",
            "Ophthalmologist",
            "Optometrist",
            "Oral And Maxillofacial Surgeon",
            "Oral Dental And Maxillofacial Surgeon",
            "Oral Medicine",
            "Oral surgeon",
            "Orthodontic Surgeon",
            "Orthodontist",
            "Orthopaedic And General Physician",
            "Orthopaedic Surgeon",
            "Orthopaedic Surgeon (Adult & Paediatric)",
            "Orthopaedic Surgeon (Hand And Upper Limb)",
            "Orthopedic",
            "Orthopedic/Neuro/Sports Rehabilitation Physiotherapist",
            "Orthopedics (Traditional Medicine)",
            "Orthoptic Assessment",
            "Orthoptist",
            "Paediatric Cardiac Surgeon",
            "Paediatric Cardiologist Paediatric Cardiothoracic Surgeon",
            "Paediatric Chest Physician",
            "Paediatric Clinical Geneticist",
            "Paediatric Dentist",
            "Paediatric Dermatologist",
            "Paediatric Endocrinologist",
            "Paediatric Endocrinologist and Diabetologist",
            "Paediatric Eye Surgeon",
            "Paediatric Gastroenterologist",
            "Paediatric Intensivist",
            "Paediatric Interventional Cardiologist",
            "Paediatric Neonatologist",
            "Paediatric Nephrologist",
            "Paediatric Neurologist",
            "Paediatric Oncologist",
            "Paediatric Oncologist(Child And Adolescents)",
            "Paediatric Optometrist",
            "Paediatric Orthopaedic Surgeon",
            "Paediatric Physiotherapist",
            "Paediatric Psychiatrist",
            "Paediatric Pulmonologist",
            "Paediatric Respiratory Chest Physician",
            "Paediatric Surgeon Paediatric Vaccinologist",
            "Paediatrician",
            "Paediatrician And Neonatologist",
            "Paediatrics And Paediatric Neurodisability",
            "Paedodontics",
            "Pain Management",
            "Pain Management in Labour",
            "Panchakarma",
            "PAP TEST",
            "Parasitologist",
            "Pathologist",
            "PCR",
            "PCR Test",
            "PCR-Test",
            "Periodontist",
            "Physical Fitness Instructor",
            "Physical Rehabilitation",
            "Physician",
            "Physician And Endocrinologists",
            "Physician/Chest Physician(Traditional Medicine)",
            "Physio Medicare",
            "Physiological Counseling",
            "Physiologist",
            "Physiotherapist",
            "Physiotherapy",
            "Physiotherapy and Rehabilitation",
            "Physiotherapy Treatment",
            "Physiotherapy Treatment with Cupping Therapy",
            "Physiotherapy Treatment with Dry Needling",
            "Physiotherapy Unit",
            "Physiotherapy/Pain And Orthopedic Neuro Rehabilitation",
            "PICU Paediatrician",
            "Plastic and Reconstructive Surgeon",
            "Plastic Eye Surgery (Cosmetic Consultation Only)",
            "Plastic Surgeon",
            "Podiatry and Biomechanics Technician",
            "Podiatry Technician",
            "Polymerase Chain Reaction Test (PCR)",
            "pre participation evaluation",
            "Pregnancy Counsellor",
            "Preventive Health Programmes",
            "Prosthesis and Orthosis",
            "Prosthetist And Orthotist",
            "Prosthodontist",
            "Psychiatrist",
            "Psychiatrist (Child And Adolescents)",
            "Psychiatrist - Adult and Old Age",
            "Psychiatrist Counsellor",
            "Psycho Social Practitioner",
            "Psychological Counselling",
            "Psychological Counselling (Ayurvedic)",
            "Psychological Counselling (Family)",
            "Psychological Counselling (Individual)",
            "Psychological Counsellor",
            "Psychological Therapy",
            "Psychologist",
            "Psychologist - Brain Rehab Workshop",
            "Psychology Support And Counseling",
            "Psychotherapist",
            "Public Health Nutritionist",
            "Pulmonary Rehabilitation Therapist",
            "Pulmonologist",
            "Pure Tone Auditory (PTA)",
            "Quarterisation Charges",
            "Radiologist",
            "Radiology",
            "Radiology Clinic",
            "Rapid Antigen Test",
            "Reconstructive Breast Surgeon",
            "Reflexology",
            "Refraction Test",
            "Rehabilitation Physician",
            "Rehabilitation Therapist",
            "Relaxation Treatments",
            "Renal Doppler",
            "Reproductive Endocrinologist",
            "Reproductive Medicine",
            "Respiratory Medicine",
            "Respiratory Physician",
            "Restorative Dentist",
            "Reverse Transcription-Polymerase Chain Reaction Test (RT-PCR)",
            "Rheumatologist",
            "Rheumatology and Rehabilitation",
            "Rheumatology and Rehabilitation Medicine",
            "S.T.D",
            "Scanning",
            "Senior Counselor",
            "Senior Orthoptist",
            "Sexual Health",
            "Sexual Medicine",
            "Sexual Wellness",
            "SFA",
            "Skin Care Adult, Paediatric & Cosmetic Dermatologist",
            "Skin Care And Cosmetic Centre - Plastic Surgeon",
            "Skin Care And Cosmetic Consultant Dermatologist",
            "Skin Care And Cosmetic Oculoplastic Surgeon",
            "Skin Diseases And General Physician",
            "Skin Hair Cosmetic Physician",
            "Skin Prick Test",
            "Skin Specialist",
            "Skin Therapy and Cosmetology",
            "Sleep Medicine",
            "Sleep Physician",
            "Sleep Study And Diagnosis",
            "Slimming",
            "Slimming and Cosmetic Gynecology",
            "Slimming and Obesity Treatment",
            "Slimming and Skin Clinic",
            "Somatic Psychologist",
            "Sonographer",
            "Sonologist",
            "Sonology Clinic",
            "Spinal Cord Injury Specialist",
            "Spinal Disorders",
            "Spinal Surgery",
            "Spine Surgeon",
            "Sports And Arthritis Surgeon",
            "Sports And Fitness Nutritionist",
            "Sports and Musculoskeletal Physiotherapist",
            "Sports Medicine",
            "Sports Physician",
            "Sports Rehabilitation",
            "Stress and Anxiety Counselling",
            "Stress Management",
            "Stress Management Clinic",
            "Stress Management Consultant",
            "Surgical Gastroenterologist",
            "Surgical Neurology",
            "Surgical Oncologist",
            "Swarna Prashan",
            "Systemic Physician",
            "Therapeutic Radiologist",
            "Therapist",
            "Throat and Nasal Allergy Specialist",
            "Thyroid And Parathyroid Surgeon",
            "Thyroid Clinic",
            "Thyroid Disease in Pregnancy",
            "Thyroidologist",
            "Tinnitus",
            "Tinnitus Retraining Therapy",
            "Tissue Doppler",
            "Tongue Tie Release",
            "Transcranial Doppler",
            "Transplant Hepatologist",
            "Trauma Surgeon",
            "Travel Clinic",
            "Travel Medicine",
            "Travel Vaccination And Consultation",
            "Travellers Medicine",
            "Travellers Vaccinations",
            "Trichologist",
            "Tropical Medicine",
            "Tropical Medicine Physician",
            "Ultrasound",
            "Ultrasound & Colour Doppler",
            "Ultrasound Clinic",
            "Ultrasound for High-Risk Pregnancy",
            "Ultrasound Scan",
            "Ultrasound Screening",
            "Underactive Thyroid",
            "Underactive Thyroid Specialist",
            "Uro Gynecologist",
            "Uro Oncologist",
            "Urologist",
            "Urologist and Andrologist",
            "Urologist and Renal Transplant Surgeon",
            "Urologist Andrologist",
            "Urology",
            "Urology And Andrology",
            "Urology Clinic",
            "Varicose Vein Treatment",
            "Vascular & Endovascular Surgeon",
            "Vascular And Endovascular Surgeon",
            "Vascular Doppler",
            "Vascular Medicine",
            "Vascular Neurologist",
            "Vascular Surgeon",
            "Venereologist",
            "Virologist",
            "Visa Medical",
            "Vocational Counsellor",
            "Voice Speech & Swallowing Therapist",
            "Weight and Stress Management",
            "Weight Loss",
            "Weight Management",
            "Women And Child Specialist",
            "Women Wellness Clinic",
            "Women's Health",
            "Women's Health Clinic",
            "Women's Hospital",
            "Womens Health Physiotherapist",
            "Work And Stress Management",
            "Work Stress Management",
            "Workplace Stress Management",
            "Workshops",
            "Yoga And Meditation",
            "Yoga Instructor",
            "Yoga Therapist"
        ];

        foreach ($specializations as $specialization) {
            Specialization::create(['name' => $specialization]);
        }
    }
}
